project:
  type: website
  output-dir: docs

website:
  title: "CURE 2027"
  navbar:
    right:
      - text: Home
        href: index.qmd

      - text: For Applicants
        menu:

          - text: How to Apply?
            href: for-applicants\how-to-apply.qmd

          - text: FAQs
            href: for-applicants\faqs.qmd

      - text: For Selected Participants
        menu:

          - text: Apply first, stupid.
            href: /#

      - text: Contact Us
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



